TELEGRAM_TOKEN: "TELEGRAM BOT TOKEN"
DATABASE_URL: "postgres://postgres@localhost:5432/berlin_vaccine_alert?sslmode=disable"

doctolib:
  - url: "https://www.doctolib.de/praxis/brandenburg-an-der-havel/corona-schutzimpfung-gzb"
    vaccine_name: "johnson" # very important to keep the name like vaccines/vaccines.go
    practice_id: "186461"
    agenda_id: "472530"
    visit_motive_id: "2877045"
    detail: "(for 40+)"
    delay: 10 # delay for sending new messages
  - url: "https://www.doctolib.de/praxis/brandenburg-an-der-havel/corona-schutzimpfung-gzb"
    vaccine_name: "astra"
    practice_id: "186461"
    agenda_id: "472530"
    visit_motive_id: "2741487"
    detail: "(for 40+)"
    delay: 10
  - url: "https://www.doctolib.de/allgemeinmedizin/berlin/sophie-ruggeberg"
    vaccine_name: "johnson"
    practice_id: "114976"
    agenda_id: "190434"
    visit_motive_id: "2886231"
  - url: "https://www.doctolib.de/allgemeinmedizin/berlin/sophie-ruggeberg"
    vaccine_name: "astra"
    practice_id: "114976"
    agenda_id: "190434"
    visit_motive_id: "2764198"
  - url: "https://www.doctolib.de/facharzt-fur-hno/berlin/babak-mayelzadeh"
    vaccine_name: "astra"
    practice_id: "120549"
    agenda_id: "305777"
    visit_motive_id: "2862419"
  - url: "https://www.doctolib.de/facharzt-fur-hno/berlin/babak-mayelzadeh"
    vaccine_name: "johnson"
    practice_id: "120549"
    agenda_id: "305777"
    visit_motive_id: "2879179"
  - url: "https://www.doctolib.de/facharzt-fur-hno/berlin/rafael-hardy"
    vaccine_name: "MRNA"
    practice_id: "22563"
    agenda_id: "56915"
    visit_motive_id: "2733996"
  - url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/oliver-staeck"
    vaccine_name: "astra"
    practice_id: "178663"
    agenda_id: "268801"
    visit_motive_id: "2784656"
  - url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/oliver-staeck"
    vaccine_name: "johnson"
    practice_id: "178663"
    agenda_id: "268801"
    visit_motive_id: "2885945"
  - url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/oliver-staeck"
    vaccine_name: "johnson"
    practice_id: "178663"
    agenda_id: "268801"
    visit_motive_id: "2885945"
  - url: "https://www.doctolib.de/praxis/berlin/praxis-fuer-orthopaedie-und-unfallchirurgie-neukoelln"
    vaccine_name: "astra"
    practice_id: "28436"
    agenda_id: "464751"
    visit_motive_id: "2811460"
  - url: "https://www.doctolib.de/medizinisches-versorgungszentrum-mvz/berlin/ambulantes-gynaekologisches-operationszentrum"
    vaccine_name: "MRNA"
    practice_id: "107774"
    agenda_id: "439400"
    visit_motive_id: "2757216"
  - url: "https://www.doctolib.de/medizinisches-versorgungszentrum-mvz/berlin/ambulantes-gynaekologisches-operationszentrum"
    vaccine_name: "astra"
    practice_id: "107774"
    agenda_id: "439400"
    visit_motive_id: "2885841"
  - url: "https://www.doctolib.de/medizinisches-versorgungszentrum-mvz/berlin/ambulantes-gynaekologisches-operationszentrum"
    vaccine_name: "johnson"
    practice_id: "107774"
    agenda_id: "439400"
    visit_motive_id: "2880391"
  - url: "https://www.doctolib.de/krankenhaus/berlin/gkh-havelhoehe-impfzentrum"
    vaccine_name: "astra"
    practice_id: "162056"
    agenda_id: "469719"
    visit_motive_id: "2836657"
  - url: "https://www.doctolib.de/krankenhaus/berlin/gkh-havelhoehe-impfzentrum"
    vaccine_name: "johnson"
    practice_id: "162056"
    agenda_id: "469719"
    visit_motive_id: "2898162"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158431"
    vaccine_name: "MRNA"
    practice_id: "158431"
    agenda_id: "457727-457733-457739-457742-457745-457726-457725-457728-457730-457736-457743-457729-457732-457738-457744-457734-457737-457740-457731"
    visit_motive_id: "2495719"
    detail: "Arena"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158434"
    vaccine_name: "MRNA"
    practice_id: "158434"
    agenda_id: "457549-457532-457533-457597-457566-457531-457558-457591-457594-457567-457593-457554-457556-457563-457569-457536-457543-457596-457529-457530"
    visit_motive_id: "2495719"
    detail: "Messe"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158437"
    vaccine_name: "MRNA"
    practice_id: "158437"
    agenda_id: "457976-457928-457927-457930-457917-457939-457975-457964-457970-457907-457924-457971-457912-457916-457922-457967-457933-457940-457968-457963-457973-457931-457915-457918-457938-457935-457979-457966-457926-457941-457937-457951-457952-457954-457947-457977-457923"
    visit_motive_id: "2537716"
    detail: "Erika-Heß-Eisstadion"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158435"
    vaccine_name: "MRNA"
    practice_id: "158435"
    agenda_id: "457195-457211-457201-457991-457205-457193"
    visit_motive_id: "2495719"
    detail: "Velodrom"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158436"
    vaccine_name: "MRNA"
    practice_id: "158436"
    agenda_id: "457250"
    visit_motive_id: "2495719"
    detail: "Flughafen Berlin-Tegel Pfizer"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-191611"
    vaccine_name: "MRNA"
    practice_id: "191611"
    agenda_id: "467906-481913-481915-481920-481917-467934-467937-467938-467939-467910-467908-467903-467907-467935-467936-467893-467895-467896-467900-467901-467905-467911-467897-467898-467912-467940-481914-481916-481919-481921-467894-467933-467899"
    visit_motive_id: "2537716"
    detail: "Flughafen Tempelhof Moderna"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-191612"
    vaccine_name: "MRNA"
    practice_id: "191612"
    agenda_id: "465555"
    visit_motive_id: "2537716"
    detail: "Flughafen Berlin-Tegel Moderna"
