TELEGRAM_TOKEN: "TELEGRAM BOT TOKEN"
DATABASE_URL: "postgres://postgres@localhost:5432/berlin_vaccine_alert?sslmode=disable"

doctolib:
  - url: "https://www.doctolib.de/praxis/brandenburg-an-der-havel/corona-schutzimpfung-gzb"
    vaccine_name: "johnson" # very important to keep the name like vaccines/vaccines.go
    practice_id: "186461"
    agenda_id: "472530"
    visit_motive_id: "2877045"
    detail: "(for 40+)"
    delay: 10 # delay for sending new messages
  - url: "https://www.doctolib.de/praxis/brandenburg-an-der-havel/corona-schutzimpfung-gzb"
    vaccine_name: "astra"
    practice_id: "186461"
    agenda_id: "472530"
    visit_motive_id: "2741487"
    detail: "(for 40+)"
    delay: 10
  - url: "https://www.doctolib.de/allgemeinmedizin/berlin/sophie-ruggeberg"
    vaccine_name: "johnson"
    practice_id: "114976"
    agenda_id: "190434"
    visit_motive_id: "2886231"
  - url: "https://www.doctolib.de/allgemeinmedizin/berlin/sophie-ruggeberg"
    vaccine_name: "astra"
    practice_id: "114976"
    agenda_id: "190434"
    visit_motive_id: "2764198"
  - url: "https://www.doctolib.de/facharzt-fur-hno/berlin/babak-mayelzadeh"
    vaccine_name: "astra"
    practice_id: "120549"
    agenda_id: "305777"
    visit_motive_id: "2862419"
  - url: "https://www.doctolib.de/facharzt-fur-hno/berlin/babak-mayelzadeh"
    vaccine_name: "johnson"
    practice_id: "120549"
    agenda_id: "305777"
    visit_motive_id: "2879179"
  - url: "https://www.doctolib.de/facharzt-fur-hno/berlin/rafael-hardy"
    vaccine_name: "MRNA"
    practice_id: "22563"
    agenda_id: "56915"
    visit_motive_id: "2733996"
  - url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/oliver-staeck"
    vaccine_name: "astra"
    practice_id: "178663"
    agenda_id: "268801"
    visit_motive_id: "2784656"
  - url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/oliver-staeck"
    vaccine_name: "johnson"
    practice_id: "178663"
    agenda_id: "268801"
    visit_motive_id: "2885945"
  - url: "https://www.doctolib.de/innere-und-allgemeinmediziner/berlin/oliver-staeck"
    vaccine_name: "johnson"
    practice_id: "178663"
    agenda_id: "268801"
    visit_motive_id: "2885945"
  - url: "https://www.doctolib.de/praxis/berlin/praxis-fuer-orthopaedie-und-unfallchirurgie-neukoelln"
    vaccine_name: "astra"
    practice_id: "28436"
    agenda_id: "464751"
    visit_motive_id: "2811460"
  - url: "https://www.doctolib.de/medizinisches-versorgungszentrum-mvz/berlin/ambulantes-gynaekologisches-operationszentrum"
    vaccine_name: "MRNA"
    practice_id: "107774"
    agenda_id: "439400"
    visit_motive_id: "2757216"
  - url: "https://www.doctolib.de/medizinisches-versorgungszentrum-mvz/berlin/ambulantes-gynaekologisches-operationszentrum"
    vaccine_name: "astra"
    practice_id: "107774"
    agenda_id: "439400"
    visit_motive_id: "2885841"
  - url: "https://www.doctolib.de/medizinisches-versorgungszentrum-mvz/berlin/ambulantes-gynaekologisches-operationszentrum"
    vaccine_name: "johnson"
    practice_id: "107774"
    agenda_id: "439400"
    visit_motive_id: "2880391"
  - url: "https://www.doctolib.de/krankenhaus/berlin/gkh-havelhoehe-impfzentrum"
    vaccine_name: "astra"
    practice_id: "162056"
    agenda_id: "469719"
    visit_motive_id: "2836657"
  - url: "https://www.doctolib.de/krankenhaus/berlin/gkh-havelhoehe-impfzentrum"
    vaccine_name: "johnson"
    practice_id: "162056"
    agenda_id: "469719"
    visit_motive_id: "2898162"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158431"
    vaccine_name: "MRNA"
    practice_id: "158431"
    agenda_id: "457703-457702-457700-457701-457704-457696-457705-457707-457709-457699-457697-457698-457710-457708-457706"
    visit_motive_id: "2495719"
    detail: "Arena"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158434"
    vaccine_name: "MRNA"
    practice_id: "158434"
    agenda_id: "457524-457527-457525-457528-457476-457480-457479"
    visit_motive_id: "2495719"
    detail: "Messe"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158437"
    vaccine_name: "MRNA"
    practice_id: "158437"
    agenda_id: "457975-457946-457964-457970-457954-457956-457961-457955-457967-457971-457968-457960-457953-457973-457959-457976-457963-457977-457979-457966-457944"
    visit_motive_id: "2537716"
    detail: "Erika-Heß-Eisstadion"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158435"
    vaccine_name: "MRNA"
    practice_id: "158435"
    agenda_id: "457212-457210-457296-457310-457299-457278-457217-457321-457215-457206-457222-457304-457306-457229-457315-457280-457291-457218-457312-457216-457319-457274-457208-457213-457227-457288-457195-457205-457193-457228-457211-457201-457991-457283"
    visit_motive_id: "2495719"
    detail: "Velodrom"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158436"
    vaccine_name: "MRNA"
    practice_id: "158436"
    agenda_id: "457250-457290-457293-457286-457289-457287"
    visit_motive_id: "2495719"
    detail: "Flughafen Berlin-Tegel Pfizer"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-191612"
    vaccine_name: "MRNA"
    practice_id: "191612"
    agenda_id: "466146-466147"
    visit_motive_id: "2537716"
    detail: "Flughafen Berlin-Tegel Moderna"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-191612"
    vaccine_name: "MRNA"
    practice_id: "191611"
    agenda_id: "481915-493644-467937-481917-467938-467939-467940-481916-481919-481921-481920-481914-493645-493648-493654-493642-493643-493647-493649-493650-493652-493653-493657-493658-481913-493634-493656-467935-467936-493635-493640-493646-493630-493631-493636-493639-493655-493632-493638"
    visit_motive_id: "2537716"
    detail: "Flughafen Berlin-Tempelhof Moderna"
  - url: "https://www.doctolib.de/institut/berlin/ciz-berlin-berlin?pid=practice-158434"
    vaccine_name: "astra"
    practice_id: "195952"
    agenda_id: "493308-493317-493328-493350-494972-493320-493322-493324-493331-493314-493329-493334-493335-493339-493338-493340-493300-493306-493326-493333-493353-493343-493345-493347-493348-493352-493298-494957-494952-494968-494981-494954-494974-494962-494977-494978-494964-494950-494966-494979"
    visit_motive_id: "2597576"
    detail: "Messe AstraZeneca"
